# Compiler, flags, and libraries
CC = gcc

CFLAGS = -g -Wall -Iinclude -Iinclude/common

# --- Configuration for Executables ---
TARGETS = test_linked_list

# --- Rules ---
all: $(TARGETS)

test_linked_list: test_linked_list.o linked_list.o
	@echo "Compiling $@..."
	$(CC) $(CFLAGS) -o $@ $^ 

test_linked_list.o: tests/test_linked_list.c include/linked_list.h include/common/common.h
	$(CC) $(CFLAGS) -c tests/test_linked_list.c

linked_list.o: src/linked_list.c include/linked_list.h include/common/common.h
	$(CC) $(CFLAGS) -c src/linked_list.c

clean:
	rm -rf $(TARGETS) *.o

# Declare targets that are not actual files
.PHONY: all clean